version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: veterinaria-app-prod:latest
    # ports:
    #   - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount custom Nginx config